Final updates to program and added meta data.

diff --git a/colorize b/colorize
--- a/colorize
+++ b/colorize
@@ -1,15 +1,25 @@
 #!/bin/bash
+# Bash Script for automatic colorization.
 
-model=/home/alanxoc3/Projects/colorization/train/models/colornet_iter_386000.caffemodel
-proto=/home/alanxoc3/Projects/colorization/train/models/model_caffe_info.prototxt
-hull=/home/alanxoc3/Projects/colorization/resources/pts_in_hull.npy
-output=/home/alanxoc3/Projects/colorization/OUT/
+# Replace the model path with your model.
+# And set the output variable to a folder if you want your images in the same
+# folder every time.
 
-if [ -f -a $1 ] ; then
-	python3 colorize.py $@ $output -m $model -p $proto -l $hull 2> /dev/null
-	status=$?
-	if [ $status != 0 ] ; then
-		echo 'There was an error with the classification. Possibly a memory error.'
+model=/path/to/your/model.caffemodel
+proto=meta/info.prototext
+hull=meta/hull.npy
+output= #demo/ # the output directory.
+for last; do true; done # Gets the last argument
+
+if [ -f -n $1 ] ; then
+	if [ -d -n $last ] ; then
+		python3 colorize.py $@ $output -m $model -p $proto -l $hull 2> /dev/null
+		status=$?
+		if [ $status != 0 ] ; then
+			echo 'An error occurred, possibly due to no memory.'
+		fi
+	else
+		echo 'Please specify a directory as the last argument.'
 	fi
 else
 	echo 'Please provide a valid filename.'
