And a final fix.

diff --git a/colorize b/colorize
--- a/colorize
+++ b/colorize
@@ -10,19 +10,23 @@
 model=models/model.caffemodel
 proto=meta/info.prototext
 hull=meta/hull.npy
-output=demo/
+output=demos/
 #gpu='-g'
 for last; do true; done # Gets the last argument
 
 if [ -f $1 ] && [ -n "$1" ] ; then
-	if [ -d $last ] && [ -n "$last" ] ; then
+	if [ -d $last ] && [ -n $last ] ; then
+		python3 colorize.py $@ -m $model -p $proto -l $hull $gpu 2> /dev/null
+		status=$?
+	elif [ -d $output ] && [ -n $output ] ; then
 		python3 colorize.py $@ $output -m $model -p $proto -l $hull $gpu 2> /dev/null
 		status=$?
-		if [ $status != 0 ] ; then
-			echo 'An error occurred, possibly due to no memory.'
-		fi
 	else
 		echo 'Please specify a directory as the last argument.'
+	fi
+
+	if [ $status != 0 ] ; then
+		echo 'An error occurred, possibly due to no memory.'
 	fi
 else
 	echo 'Please provide a valid filename.'
